# This is a YAML format configuration file
app:
  log:
    # path "exe path" by default, not modifiable
    # log_file_name: the log file save name
    log_file_name: applog.html
    log_file_count: 5
    # log_file_size: size default MB
    log_file_size: 10M
    # log_level: trace=0, debug = 1,info = 2, warn = 3, error = 4
    log_level: 1
  database:
    # rdbms: Server type, postgresql,mysql or sqlite3, "postgresql" by default
    rdbms: postgresql
    # host: Server address,localhost by default
    host: localhost
    # port: Server port, 5432 by default
    port: 5132
    # dbname: Database name
    dbname: integration
    # user: 'postgres' by default
    user: 'postgres'
    # passwd: release '' by default,password security considerations
    passwd: ''
product:
  # type: circle or line,cap; required current choosed device type
  type: circle
plc:
  # this block define the kind of registers address and size
  # normal_address interval 500ms
  # realtime_address interval 5ms
  # # # product line device # # #
  # host: 192.168.123.10
  # port: 502
  # normal_address: 40001
  # normal_size: 81
  # realtime_address: 40081
  # realtime_size: 1
  # write_address: 40001
  # write_size: 81
  # # # product circle device # # #
  host: 192.168.123.1      
  port: 502         
  normal_address: 412289
  normal_size: 400
  realtime_address: 412642
  realtime_size: 14
  write_address: 412689
  write_size: 316
  # # product cap device # # #
  # host: 192.168.123.10
  # port: 502
  # normal_address: 40001
  # normal_size: 116
  # realtime_address: 40117
  # realtime_size: 1
  # write_address: 0
  # write_size: 0
algorithm:
  url_ocr: 'http://192.168.101.8:5001/paddleOCR'
  url_predict: 'http://127.0.0.1:5000/predict_tangle'
  ws_tangle: 'ws://localhost:5000/'
  ws_tangleCheck: 'ws://localhost:5002/'
  ws_ocr: 'ws://localhost:5001/'
domino:                                                 
  host: 127.0.0.1
  port: 20001                     
cognex:
  host: 192.168.60.121
  port: 23
permission:
  host: 192.168.123.100
  port: 2000
baumer:
  interface: 
    mac: CC-82-7F-3C-04-F7
    ip: 192.168.60.60
    mask: 255.255.255.0

  camera:
    # display_window: Location;LocateCheck;OCR; only this value
    # expose: float, expose time unit millisecond
    # gain: int, range 0 ~ 100
    # width: int, capture image width px
    # height: int, capture image height px
    - sn_number: 700009842711
      ip: 192.168.60.73
      mask: 255.255.255.0
      display_window: Location
      expose: 0.2
      gain: 1
      width: 1024
      height: 1024
      offset_x: 928
      offset_y: 498
    - sn_number: 700009429371
      ip: 192.168.60.72
      mask: 255.255.255.0
      display_window: LocateCheck
      expose: 0.8
      gain: 3
      width: 800
      height: 800
      offset_x: 960
      offset_y: 968
    - sn_number: 700009429365
      ip: 192.168.60.1
      mask: 255.255.255.0
      display_window: OCR
      expose: 0.8
      gain: 5
      width: 800
      height: 800
      offset_x: 880
      offset_y: 618
